/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

package com.MAVLink.enums;

/**
 * 
 */
public class USV_CHANNEL_TYPE {
   public static final int USV_CHANNEL_TYPE_UDP = 0; /* udp | */
   public static final int USV_CHANNEL_TYPE_WS = 1; /* websocket | */
   public static final int USV_CHANNEL_TYPE_MQTT = 2; /* mqtt | */
   public static final int USV_CHANNEL_TYPE_SERIAL_PORT = 3; /* serial port | */
   public static final int USV_CHANNEL_TYPE_ENUM_END = 4; /*  | */
}