/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

package com.MAVLink.enums;

/**
 * 
 */
public class USV_LINK_TYPE {
   public static final int USV_LINK_TYPE_NETWORK = 0; /* network | */
   public static final int USV_LINK_TYPE_RADIO = 1; /* radio | */
   public static final int USV_LINK_TYPE_SATELLITE = 2; /* satellite | */
   public static final int USV_LINK_TYPE_ENUM_END = 3; /*  | */
}