/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

package com.MAVLink.enums;

/**
 * 
 */
public class USV_MSG_SRC {
   public static final int USV_MSG_SRC_USV = 0; /* usv | */
   public static final int USV_MSG_SRC_GCS = 1; /* gcs | */
   public static final int USV_MSG_SRC_SERVER = 2; /* server | */
   public static final int USV_MSG_SRC_ENUM_END = 3; /*  | */
}