/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

// MESSAGE USV_REGISTER_REQUEST PACKING
package com.MAVLink.USV;
import com.MAVLink.MAVLinkPacket;
import com.MAVLink.Messages.MAVLinkMessage;
import com.MAVLink.Messages.MAVLinkPayload;
import com.MAVLink.Messages.Units;
import com.MAVLink.Messages.Description;

/**
 * usv/ugc register request
 */
public class msg_usv_register_request extends MAVLinkMessage {

    public static final int MAVLINK_MSG_ID_USV_REGISTER_REQUEST = 50001;
    public static final int MAVLINK_MSG_LENGTH = 3;
    private static final long serialVersionUID = MAVLINK_MSG_ID_USV_REGISTER_REQUEST;

    
    /**
     * msg source
     */
    @Description("msg source")
    @Units("")
    public short msg_src;
    
    /**
     * msg source
     */
    @Description("msg source")
    @Units("")
    public short link_type;
    
    /**
     * msg source
     */
    @Description("msg source")
    @Units("")
    public short channel_type;
    

    /**
     * Generates the payload for a mavlink message for a message of this type
     * @return
     */
    @Override
    public MAVLinkPacket pack() {
        MAVLinkPacket packet = new MAVLinkPacket(MAVLINK_MSG_LENGTH,isMavlink2);
        packet.sysid = sysid;
        packet.compid = compid;
        packet.msgid = MAVLINK_MSG_ID_USV_REGISTER_REQUEST;

        packet.payload.putUnsignedByte(msg_src);
        packet.payload.putUnsignedByte(link_type);
        packet.payload.putUnsignedByte(channel_type);
        
        if (isMavlink2) {
            
        }
        return packet;
    }

    /**
     * Decode a usv_register_request message into this class fields
     *
     * @param payload The message to decode
     */
    @Override
    public void unpack(MAVLinkPayload payload) {
        payload.resetIndex();

        this.msg_src = payload.getUnsignedByte();
        this.link_type = payload.getUnsignedByte();
        this.channel_type = payload.getUnsignedByte();
        
        if (isMavlink2) {
            
        }
    }

    /**
     * Constructor for a new message, just initializes the msgid
     */
    public msg_usv_register_request() {
        this.msgid = MAVLINK_MSG_ID_USV_REGISTER_REQUEST;
    }

    /**
     * Constructor for a new message, initializes msgid and all payload variables
     */
    public msg_usv_register_request( short msg_src, short link_type, short channel_type) {
        this.msgid = MAVLINK_MSG_ID_USV_REGISTER_REQUEST;

        this.msg_src = msg_src;
        this.link_type = link_type;
        this.channel_type = channel_type;
        
    }

    /**
     * Constructor for a new message, initializes everything
     */
    public msg_usv_register_request( short msg_src, short link_type, short channel_type, int sysid, int compid, boolean isMavlink2) {
        this.msgid = MAVLINK_MSG_ID_USV_REGISTER_REQUEST;
        this.sysid = sysid;
        this.compid = compid;
        this.isMavlink2 = isMavlink2;

        this.msg_src = msg_src;
        this.link_type = link_type;
        this.channel_type = channel_type;
        
    }

    /**
     * Constructor for a new message, initializes the message with the payload
     * from a mavlink packet
     *
     */
    public msg_usv_register_request(MAVLinkPacket mavLinkPacket) {
        this.msgid = MAVLINK_MSG_ID_USV_REGISTER_REQUEST;

        this.sysid = mavLinkPacket.sysid;
        this.compid = mavLinkPacket.compid;
        this.isMavlink2 = mavLinkPacket.isMavlink2;
        unpack(mavLinkPacket.payload);
    }

          
    /**
     * Returns a string with the MSG name and data
     */
    @Override
    public String toString() {
        return "MAVLINK_MSG_ID_USV_REGISTER_REQUEST - sysid:"+sysid+" compid:"+compid+" msg_src:"+msg_src+" link_type:"+link_type+" channel_type:"+channel_type+"";
    }

    /**
     * Returns a human-readable string of the name of the message
     */
    @Override
    public String name() {
        return "MAVLINK_MSG_ID_USV_REGISTER_REQUEST";
    }
}
        