/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

// MESSAGE USV_DEREGISTER_RESPONSE PACKING
package com.MAVLink.USV;
import com.MAVLink.MAVLinkPacket;
import com.MAVLink.Messages.MAVLinkMessage;
import com.MAVLink.Messages.MAVLinkPayload;
import com.MAVLink.Messages.Units;
import com.MAVLink.Messages.Description;

/**
 * usv/ugc deregister response
 */
public class msg_usv_deregister_response extends MAVLinkMessage {

    public static final int MAVLINK_MSG_ID_USV_DEREGISTER_RESPONSE = 50004;
    public static final int MAVLINK_MSG_LENGTH = 1;
    private static final long serialVersionUID = MAVLINK_MSG_ID_USV_DEREGISTER_RESPONSE;

    
    /**
     * 1: deregister succeed. 0: deregister failed.
     */
    @Description("1: deregister succeed. 0: deregister failed.")
    @Units("")
    public short ack;
    

    /**
     * Generates the payload for a mavlink message for a message of this type
     * @return
     */
    @Override
    public MAVLinkPacket pack() {
        MAVLinkPacket packet = new MAVLinkPacket(MAVLINK_MSG_LENGTH,isMavlink2);
        packet.sysid = sysid;
        packet.compid = compid;
        packet.msgid = MAVLINK_MSG_ID_USV_DEREGISTER_RESPONSE;

        packet.payload.putUnsignedByte(ack);
        
        if (isMavlink2) {
            
        }
        return packet;
    }

    /**
     * Decode a usv_deregister_response message into this class fields
     *
     * @param payload The message to decode
     */
    @Override
    public void unpack(MAVLinkPayload payload) {
        payload.resetIndex();

        this.ack = payload.getUnsignedByte();
        
        if (isMavlink2) {
            
        }
    }

    /**
     * Constructor for a new message, just initializes the msgid
     */
    public msg_usv_deregister_response() {
        this.msgid = MAVLINK_MSG_ID_USV_DEREGISTER_RESPONSE;
    }

    /**
     * Constructor for a new message, initializes msgid and all payload variables
     */
    public msg_usv_deregister_response( short ack) {
        this.msgid = MAVLINK_MSG_ID_USV_DEREGISTER_RESPONSE;

        this.ack = ack;
        
    }

    /**
     * Constructor for a new message, initializes everything
     */
    public msg_usv_deregister_response( short ack, int sysid, int compid, boolean isMavlink2) {
        this.msgid = MAVLINK_MSG_ID_USV_DEREGISTER_RESPONSE;
        this.sysid = sysid;
        this.compid = compid;
        this.isMavlink2 = isMavlink2;

        this.ack = ack;
        
    }

    /**
     * Constructor for a new message, initializes the message with the payload
     * from a mavlink packet
     *
     */
    public msg_usv_deregister_response(MAVLinkPacket mavLinkPacket) {
        this.msgid = MAVLINK_MSG_ID_USV_DEREGISTER_RESPONSE;

        this.sysid = mavLinkPacket.sysid;
        this.compid = mavLinkPacket.compid;
        this.isMavlink2 = mavLinkPacket.isMavlink2;
        unpack(mavLinkPacket.payload);
    }

      
    /**
     * Returns a string with the MSG name and data
     */
    @Override
    public String toString() {
        return "MAVLINK_MSG_ID_USV_DEREGISTER_RESPONSE - sysid:"+sysid+" compid:"+compid+" ack:"+ack+"";
    }

    /**
     * Returns a human-readable string of the name of the message
     */
    @Override
    public String name() {
        return "MAVLINK_MSG_ID_USV_DEREGISTER_RESPONSE";
    }
}
        