/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

// MESSAGE USV_CONNECT_RESPONSE PACKING
package com.MAVLink.USV;
import com.MAVLink.MAVLinkPacket;
import com.MAVLink.Messages.MAVLinkMessage;
import com.MAVLink.Messages.MAVLinkPayload;
import com.MAVLink.Messages.Units;
import com.MAVLink.Messages.Description;

/**
 * usv connect response
 */
public class msg_usv_connect_response extends MAVLinkMessage {

    public static final int MAVLINK_MSG_ID_USV_CONNECT_RESPONSE = 50006;
    public static final int MAVLINK_MSG_LENGTH = 2;
    private static final long serialVersionUID = MAVLINK_MSG_ID_USV_CONNECT_RESPONSE;

    
    /**
     * gcs system id.
     */
    @Description("gcs system id.")
    @Units("")
    public short target_system;
    
    /**
     * 0: connect failed or usv connected by other gcs. 1: connect succeed.
     */
    @Description("0: connect failed or usv connected by other gcs. 1: connect succeed.")
    @Units("")
    public short ack;
    

    /**
     * Generates the payload for a mavlink message for a message of this type
     * @return
     */
    @Override
    public MAVLinkPacket pack() {
        MAVLinkPacket packet = new MAVLinkPacket(MAVLINK_MSG_LENGTH,isMavlink2);
        packet.sysid = sysid;
        packet.compid = compid;
        packet.msgid = MAVLINK_MSG_ID_USV_CONNECT_RESPONSE;

        packet.payload.putUnsignedByte(target_system);
        packet.payload.putUnsignedByte(ack);
        
        if (isMavlink2) {
            
        }
        return packet;
    }

    /**
     * Decode a usv_connect_response message into this class fields
     *
     * @param payload The message to decode
     */
    @Override
    public void unpack(MAVLinkPayload payload) {
        payload.resetIndex();

        this.target_system = payload.getUnsignedByte();
        this.ack = payload.getUnsignedByte();
        
        if (isMavlink2) {
            
        }
    }

    /**
     * Constructor for a new message, just initializes the msgid
     */
    public msg_usv_connect_response() {
        this.msgid = MAVLINK_MSG_ID_USV_CONNECT_RESPONSE;
    }

    /**
     * Constructor for a new message, initializes msgid and all payload variables
     */
    public msg_usv_connect_response( short target_system, short ack) {
        this.msgid = MAVLINK_MSG_ID_USV_CONNECT_RESPONSE;

        this.target_system = target_system;
        this.ack = ack;
        
    }

    /**
     * Constructor for a new message, initializes everything
     */
    public msg_usv_connect_response( short target_system, short ack, int sysid, int compid, boolean isMavlink2) {
        this.msgid = MAVLINK_MSG_ID_USV_CONNECT_RESPONSE;
        this.sysid = sysid;
        this.compid = compid;
        this.isMavlink2 = isMavlink2;

        this.target_system = target_system;
        this.ack = ack;
        
    }

    /**
     * Constructor for a new message, initializes the message with the payload
     * from a mavlink packet
     *
     */
    public msg_usv_connect_response(MAVLinkPacket mavLinkPacket) {
        this.msgid = MAVLINK_MSG_ID_USV_CONNECT_RESPONSE;

        this.sysid = mavLinkPacket.sysid;
        this.compid = mavLinkPacket.compid;
        this.isMavlink2 = mavLinkPacket.isMavlink2;
        unpack(mavLinkPacket.payload);
    }

        
    /**
     * Returns a string with the MSG name and data
     */
    @Override
    public String toString() {
        return "MAVLINK_MSG_ID_USV_CONNECT_RESPONSE - sysid:"+sysid+" compid:"+compid+" target_system:"+target_system+" ack:"+ack+"";
    }

    /**
     * Returns a human-readable string of the name of the message
     */
    @Override
    public String name() {
        return "MAVLINK_MSG_ID_USV_CONNECT_RESPONSE";
    }
}
        